project:
  type: website
  output-dir: docs
website:
  title: "BIBFRAME: ¿En español?"
  page-footer: "Yale University Library"
  back-to-top-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Acerca de"
        href: about.qmd
      - sidebar:dia1
      - sidebar:dia2
      - sidebar:dia3
      - sidebar:dia4
      - sidebar:dia5
  sidebar:
    - id: dia1
      search: false
      title: "Día 1"
      style: "docked"
      background: light
      href: 01-day/00-day1-ProgramaSugerido.qmd
      contents:
      - href: 01-day/00-day1-ProgramaSugerido.qmd
        text: Introducción Día 1 
        contents:
        - 01-day/00-day1-ProgramaSugerido.qmd
        - 01-day/01-day1-Resumen.qmd
    - id: dia2
      title: "Día 2"
      href: 02-day/00-day2-ProgramaSugerido.qmd
      contents:
      - href: 02-day/00-day2-ProgramaSugerido.qmd
        text: Introducción Día 2
        contents:
        - 02-day/00-day2-ProgramaSugerido.qmd
        - 02-day/01-day2-Resumen.qmd
    - id: dia3
      title: "Día 3"
      href: 03-day/00-day3-ProgramaSugerido.qmd
      contents:
      - href: 03-day/00-day3-ProgramaSugerido.qmd
        text: Introducción Día 3
        contents:
        - 03-day/00-day3-ProgramaSugerido.qmd
        - 03-day/01-day3-Resumen.qmd
    - id: dia4
      title: "Día 4"
      href: 04-day/00-day4-ProgramaSugerido.qmd
      contents:
      - href: 04-day/00-day4-ProgramaSugerido.qmd
        text: Introducción Día 4
        contents:
        - 04-day/00-day4-ProgramaSugerido.qmd
        - 04-day/01-day4-Resumen.qmd
    - id: dia5
      title: "Día 5"
      href: 05-day/00-day5-ProgramaSugerido.qmd
      contents:
      - href: 05-day/00-day5-ProgramaSugerido.qmd
        text: Introducción Día 5
        contents:
        - 05-day/00-day5-ProgramaSugerido.qmd
        - 05-day/01-day5-Resumen.qmd
format:
  html:
    theme: yeti